// MockAIPluginGenerator.swift
// menubar01 — AI Plugin Generator (M1)
//
// Deterministic, network-free implementation of `AIPluginGenerator`.
// It always returns the same hard-coded "Echo" plugin regardless of
// the input. The `promptId` is `SHA256(request + "|" + context.model)`
// so reproducibility is verifiable from a unit test.

import CryptoKit
import Foundation
import os

/// Deterministic mock that returns a hard-coded `GeneratedPlugin` for
/// every call. The point of M1 is to wire up the protocol surface and
/// the bundle-encoding path against a real (but trivial) plugin; the
/// real LLM call lands in M2+.
///
/// `promptId` is `SHA256(request + "|" + context.model)`, so calling
/// `generate` twice with the same `(request, context.model)` always
/// yields the same hash. Different requests or different model
/// identifiers produce different hashes.
public final class MockAIPluginGenerator: AIPluginGenerator {
    /// The version string the mock reports in
    /// `GeneratedPlugin.promptVersion`. Bumping this signals that the
    /// generator's template or generation logic has changed.
    public static let mockPromptVersion = "v1.0-mock"

    /// Stable label the M5 history-UI filter picker groups this
    /// generator's entries under. Surfaced through
    /// `AIPluginGenerator.providerName` so the user can narrow
    /// the sidebar to "Mock" runs only.
    public static let providerDisplayName = "Mock"

    public init() {}

    /// `providerName` for the mock generator. Mirrors the
    /// static `providerDisplayName` so call sites can read
    /// either the static or the instance form interchangeably.
    public var providerName: String? { Self.providerDisplayName }

    public func generate(
        request: String,
        context: AIGeneratorContext
    ) async throws -> GeneratedPlugin {
        let promptId = Self.promptId(for: request, model: context.model)
        return Self.makeMockPlugin(promptId: promptId, context: context)
    }

    // MARK: - Hashing

    /// Computes the deterministic `promptId` from
    /// `SHA256(request + "|" + model)`. Returns the lowercased hex
    /// digest so it can be safely embedded in a manifest filename.
    public static func promptId(for request: String, model: String) -> String {
        var hasher = SHA256()
        hasher.update(data: Data(request.utf8))
        hasher.update(data: Data("|".utf8))
        hasher.update(data: Data(model.utf8))
        let digest = hasher.finalize()
        return digest.map { String(format: "%02x", $0) }.joined()
    }

    // MARK: - Mock Payload

    /// Builds the hard-coded "Echo" plugin. Exposed internally so the
    /// tests can assert against a known value without going through
    /// the async `generate` path.
    static func makeMockPlugin(promptId: String, context: AIGeneratorContext) -> GeneratedPlugin {
        var manifest = PluginManifest()
        manifest.name = "Echo"
        manifest.version = "1.0.0"
        manifest.description = "Echoes the MENUBAR01_PARAM_PROMPT parameter back into the menu."
        manifest.author = "menubar01 AI (mock)"
        manifest.type = .Executable
        manifest.entry = "echo.sh"
        manifest.refreshInterval = context.refreshIntervalSeconds.map(Double.init) ?? 5
        manifest.runInBash = false

        let promptParam = PluginManifestParameter(
            name: "PROMPT",
            type: .string,
            default: "hello from the menubar01 AI mock",
            description: "Text to echo back into the menu",
            options: nil
        )
        manifest.parameters = [promptParam]

        let entryScript = """
        #!/bin/zsh
        # Auto-generated by menubar01 AIPluginGenerator (mock).
        # promptId=\(promptId)
        echo "echo: $MENUBAR01_PARAM_PROMPT"
        """

        let explanation = """
        Mock generator for v1. This plugin echoes the `PROMPT` parameter
        back into the menu bar. Real LLM-backed generation arrives in M2.
        """

        return GeneratedPlugin(
            manifest: manifest,
            entryScript: entryScript,
            explanation: explanation,
            promptId: promptId,
            promptVersion: mockPromptVersion
        )
    }
}
