// AIGeneratorEndpointHostTests.swift
// menubar01 — AI Plugin Generator (M5+ history endpoint host)
//
// Swift Testing coverage for the M5+ history-endpoint-host
// follow-up. The M5 history UI surfaces "Generated by
// `<model>` at `<host>`" alongside each entry, so the
// `AIGeneratorHistoryEntry` value type records the endpoint
// host (when known) and the `AIPluginGenerator` protocol
// exposes the host as an optional computed property.
//
// Backward-compat: a `response.json` file written before this
// field existed must still decode cleanly. The hand-rolled
// `AIGeneratorHistoryEntry.init(from:)` uses
// `decodeIfPresent(_:forKey:)` for the new key so an absent
// key decodes to `nil` rather than throwing.

import Foundation
import Testing

@testable import menubar01

// MARK: - Helpers

/// Builds a `GeneratedPlugin` for the round-trip tests. Mirrors
/// the v1 "Echo" shape used throughout the M1–M5 tests so the
/// entry's flattened `manifest` bytes are stable.
private func makeTestPlugin(promptId: String) -> GeneratedPlugin {
    var manifest = PluginManifest()
    manifest.name = "Echo"
    manifest.version = "1.0.0"
    manifest.description = "Test description"
    manifest.author = "menubar01 tests"
    manifest.type = .Executable
    manifest.entry = "echo.sh"
    manifest.refreshInterval = 5
    return GeneratedPlugin(
        manifest: manifest,
        entryScript: "#!/bin/zsh\necho \(promptId)\n",
        explanation: "Test explanation",
        promptId: promptId,
        promptVersion: "v1.0-test"
    )
}

// MARK: - entry-level Codable round-trip

struct AIGeneratorHistoryEntryEndpointHostTests {

    @Test func testEntry_encodesAndDecodesEndpointHost() throws {
        // Round-trip an entry whose `endpointHost` is set; the
        // host must survive the encode → decode cycle.
        let original = AIGeneratorHistoryEntry(
            promptId: "remote-1",
            createdAt: Date(timeIntervalSince1970: 1_700_000_000),
            request: "show weather",
            model: "gpt-4o-mini",
            plugin: makeTestPlugin(promptId: "remote-1"),
            menuTreeJSON: nil,
            endpointHost: "api.openai.com"
        )

        // Use the same pretty-printed, sorted-key settings the
        // on-disk `FileSystemAIGeneratorHistoryStore` uses so the
        // JSON we assert on matches the bytes the production code
        // writes to `response.json`.
        let encoder = FileSystemAIGeneratorHistoryStore.defaultEncoder()
        let data = try encoder.encode(original)

        // The on-disk JSON must contain the host verbatim so a
        // human inspecting `response.json` in a text editor can
        // see which provider produced the entry.
        let json = try #require(String(data: data, encoding: .utf8))
        #expect(json.contains("\"endpointHost\" : \"api.openai.com\""))

        let decoder = FileSystemAIGeneratorHistoryStore.defaultDecoder()
        let decoded = try decoder.decode(AIGeneratorHistoryEntry.self, from: data)
        #expect(decoded == original)
        #expect(decoded.endpointHost == "api.openai.com")
    }

    @Test func testEntry_decodesMissingEndpointHostAsNil() throws {
        // An entry constructed with `endpointHost: nil` (the
        // default) must round-trip cleanly; the on-disk JSON
        // omits the key and decoding leaves the field at `nil`.
        let original = AIGeneratorHistoryEntry(
            promptId: "no-host",
            createdAt: Date(timeIntervalSince1970: 1_700_000_001),
            request: "list something",
            model: "gpt-4o-mini",
            plugin: makeTestPlugin(promptId: "no-host")
        )
        #expect(original.endpointHost == nil)

        let encoder = JSONEncoder()
        let data = try encoder.encode(original)
        let json = try #require(String(data: data, encoding: .utf8))
        // The default-nil case must not emit the key at all,
        // matching the existing `menuTreeJSON` field's
        // `encodeIfPresent` convention.
        #expect(!json.contains("endpointHost"))

        let decoder = JSONDecoder()
        let decoded = try decoder.decode(AIGeneratorHistoryEntry.self, from: data)
        #expect(decoded.endpointHost == nil)
        #expect(decoded == original)
    }

    @Test func testEntry_decodesLegacyJSONWithoutEndpointHostKey() throws {
        // The v1 on-disk format did not include `endpointHost`.
        // The hand-rolled `init(from:)` must treat an absent
        // key as `nil` (rather than throwing) so existing
        // `response.json` files written before this change
        // continue to load.
        let legacyJSON = """
        {
          "createdAt" : 1700000000,
          "model" : "gpt-4o-mini",
          "pluginEntryScript" : "#!/bin/zsh\\necho legacy\\n",
          "pluginExplanation" : "legacy entry",
          "pluginManifest" : {
            "author" : "menubar01 tests",
            "description" : "Test description",
            "entry" : "echo.sh",
            "name" : "Echo",
            "refreshInterval" : 5,
            "type" : "Executable",
            "version" : "1.0.0"
          },
          "pluginPromptVersion" : "v1.0-legacy",
          "promptId" : "legacy-1",
          "request" : "legacy request"
        }
        """
        // `createdAt: 1700000000` is the v1 Unix-seconds
        // encoding; switch the decoder to `secondsSince1970`
        // to match the legacy on-disk format the file was
        // written with.
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .secondsSince1970
        let data = Data(legacyJSON.utf8)

        let decoded = try decoder.decode(
            AIGeneratorHistoryEntry.self,
            from: data
        )

        #expect(decoded.promptId == "legacy-1")
        #expect(decoded.request == "legacy request")
        #expect(decoded.model == "gpt-4o-mini")
        #expect(decoded.plugin.promptVersion == "v1.0-legacy")
        #expect(decoded.endpointHost == nil)
    }
}

// MARK: - AIPluginGenerator.endpointHost

struct AIPluginGeneratorEndpointHostTests {

    @Test func testRemoteAIGenerator_exposesEndpointHost() {
        // The remote provider dials a real URL; the protocol
        // accessor must surface `endpoint.host` so the
        // view-model can persist it on the history entry.
        let endpoint = URL(string: "https://api.openai.com")!
        let generator = RemoteAIPluginGenerator(
            endpoint: endpoint,
            apiKey: "k"
        )
        #expect(generator.endpointHost == "api.openai.com")
    }

    @Test func testMockGenerator_endpointHostIsNil() {
        // The mock is network-free; the protocol default
        // returns `nil` and the mock must inherit it.
        let generator = MockAIPluginGenerator()
        #expect(generator.endpointHost == nil)
    }
}
